// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	customer "github/zjzjzjzj1874/go-zero-temp/user/internal/handler/customer"
	staff "github/zjzjzjzj1874/go-zero-temp/user/internal/handler/staff"
	swagger "github/zjzjzjzj1874/go-zero-temp/user/internal/handler/swagger"
	"github/zjzjzjzj1874/go-zero-temp/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Recover, serverCtx.Log},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/login-phone",
					Handler: customer.LoginPhoneHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/login-wechat",
					Handler: customer.LoginWechatHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/bind",
					Handler: customer.LoginBindPhoneHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/customers"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Recover, serverCtx.Log},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/get-phone-auth",
					Handler: customer.GetCellPhoneAuthHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/customers"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Permission},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/add-staff",
					Handler: staff.AddStaffHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/user/delete-staff/:id",
					Handler: staff.DeleteStaffHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/change-staff",
					Handler: staff.ChangeStaffHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/get-staff/:id",
					Handler: staff.GetStaffHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/list-staffs",
					Handler: staff.ListStaffsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login-staff",
				Handler: staff.LoginStaffHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/liveness",
				Handler: LivenessHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/swagger",
				Handler: swagger.SwaggerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)
}
