// Code generated by goctl. DO NOT EDIT.
package types

type OperatorMeta struct {
	ID   string `json:"id,omitempty" bson:"_id,omitempty"`
	Name string `json:"name" bson:"name" description:"名称"`
}

type QueryOptions struct {
	Page          int64    `form:"page,default=1,optional" description:"当前页"`
	PageSize      int64    `form:"page_size,default=10,optional" description:"每页数量"`
	Search        string   `form:"search,optional" description:"搜索"`
	SortKeys      string   `form:"sort_keys,optional,default=-create_time" description:"排序"`
	ProjectFields []string `form:"projectFields,optional" description:"排序"`
	ExcludeFields []string `form:"excludeFields,optional" description:"排序"`
}

type GetCellPhoneAuthReq struct {
	Phone string `json:"phone" description:"客户电话"`
}

type GetCellPhoneAuthResp struct {
	Code int32  `json:"code,default=200" description:"返回码"`
	Msg  string `json:"msg,default=请求成功" description:"消息说明"`
}

type LoginPhoneData struct {
	Token      string `json:"token" description:"jwt"`
	Extra      string `json:"extra" description:"额外信息"`
	HeadImgUrl string `json:"head_img_url" description:"用户头像:微信登陆有,如果没值就用默认"`
}

type LoginPhoneReq struct {
	Phone              string `json:"phone" description:"手机号"`
	PhoneAuth          string `json:"phone_auth" description:"手机验证码"`
	BrowserFingerprint string `json:"browser_fingerprint" description:"浏览器指纹"`
}

type LoginPhoneResp struct {
	Code int32           `json:"code,default=200" description:"返回码"`
	Msg  string          `json:"msg,default=请求成功" description:"消息说明"`
	Data *LoginPhoneData `json:"data" description:"登录数据"`
}

type LoginBindPhoneReq struct {
	Phone              string `json:"phone" description:"手机号"`
	PhoneAuth          string `json:"phone_auth" description:"手机验证码"`
	WechatId           string `json:"wechat_id" description:"微信ID"`
	BrowserFingerprint string `json:"browser_fingerprint" description:"浏览器指纹"`
}

type LoginBindPhoneResp struct {
	Code int32           `json:"code,default=200" description:"返回码"`
	Msg  string          `json:"msg,default=请求成功" description:"消息说明"`
	Data *LoginPhoneData `json:"data" description:"登录数据"`
}

type LoginWechatReq struct {
	Code               string `json:"code" description:"登录Code"`
	BrowserFingerprint string `json:"browser_fingerprint" description:"浏览器指纹"`
}

type LoginWechatResp struct {
	Code int32           `json:"code,default=200" description:"返回码"`
	Msg  string          `json:"msg,default=请求成功" description:"消息说明"`
	Data *LoginPhoneData `json:"data" description:"登录数据"`
}

type LoginStaffData struct {
	Uid    string `json:"uid"  description:"_id"`
	Name   string `json:"name" description:"姓名"`
	Email  string `json:"email" description:"邮箱"`
	Token  string `json:"token" description:"jwt"`
	Expire int64  `json:"expire" description:"过期时间"`
}

type LoginStaffReq struct {
	Ticket string `json:"ticket" description:"登录ticket"`
}

type LoginStaffResp struct {
	Code int32           `json:"code,default=200" description:"返回码"`
	Msg  string          `json:"msg,default=请求成功" description:"消息说明"`
	Data *LoginStaffData `json:"data" description:"jwt数据"`
}

type AddStaffReq struct {
	Name  string `json:"name" description:"姓名"`
	Email string `json:"email" description:"用户邮箱"`
	OnJob int32  `json:"on_job"  description:"是否在职"`
}

type AddStaffResp struct {
	Code int32  `json:"code,default=200" description:"返回码"`
	Msg  string `json:"msg,default=请求成功" description:"消息说明"`
}

type DeleteStaffReq struct {
	Id string `path:"id" description:"objectId"`
}

type DeleteStaffResp struct {
	Code int32  `json:"code,default=200" description:"返回码"`
	Msg  string `json:"msg,default=请求成功" description:"消息说明"`
}

type ChangeStaffReq struct {
	Id    string `json:"id" description:"objectId"`
	Name  string `json:"name,optional" description:"姓名"`
	Email string `json:"email,optional" description:"用户邮箱"`
	OnJob int32  `json:"on_job,optional"  description:"是否在职"`
}

type ChangeStaffResp struct {
	Code int32  `json:"code,default=200" description:"返回码"`
	Msg  string `json:"msg,default=请求成功" description:"消息说明"`
}

type StaffInfo struct {
	ID         string   `json:"id" description:"objectId"`
	Name       string   `json:"name" description:"姓名"`
	Phone      string   `json:"phone" description:"用户电话"`
	Email      string   `json:"email" description:"邮箱"`
	OnJob      int32    `json:"on_job" description:"是否在职"`
	Roles      []string `json:"roles" description:"角色列表,角色需要进行分配"`
	CreateTime string   `json:"create_time" description:"创建时间"`
	UpdateTime string   `json:"update_time" description:"更新时间"`
}

type GetStaffReq struct {
	Id string `path:"id" description:"objectId"`
}

type GetStaffResp struct {
	Code int32      `json:"code,default=200" description:"返回码"`
	Msg  string     `json:"msg,default=请求成功" description:"消息说明"`
	Data *StaffInfo `json:"data" description:"jwt数据"`
}

type ListStaffsReq struct {
	Page          int32    `form:"page,optional" description:"当前页"`
	PageSize      int32    `form:"page_size,optional" description:"每页数量"`
	Name          string   `form:"name,optional" description:"姓名"`
	Email         string   `form:"email,optional" description:"邮箱"`
	Search        string   `form:"search,optional" description:"搜索"`
	SortKeys      string   `form:"sortKeys,optional" description:"排序"`
	ProjectFields []string `form:"project_fields,optional" description:"返回字段"`
	ExcludeFields []string `form:"exclude_fields,optional" description:"排除字段"`
}

type ListStaffsResp struct {
	Code      int32       `json:"code,default=200" description:"返回码"`
	Msg       string      `json:"msg,default=请求成功" description:"消息说明"`
	Data      []StaffInfo `json:"data" description:"员工列表"`
	Count     int64       `json:"count" description:"总数"`
	TotalPage int64       `json:"total_page" description:"总页数"`
}
