// Code generated by goctl. DO NOT EDIT.
package types

type Role struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`        // 角色名称
	Description string `json:"description"` // 角色描述
	Status      int    `json:"status"`      // 状态：0-禁用 1-启用
	CreateTime  int64  `json:"createTime"`
	UpdateTime  int64  `json:"updateTime"`
}

type CreateRoleReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
}

type UpdateRoleReq struct {
	Id          int64  `json:"id"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Status      int    `json:"status,optional"`
}

type RoleListReq struct {
	Page     int    `json:"page,optional,default=1"`
	PageSize int    `json:"pageSize,optional,default=20"`
	Name     string `json:"name,optional"`
	Status   int    `json:"status,optional,default=-1"`
}

type RoleListResp struct {
	Total int64  `json:"total"`
	List  []Role `json:"list"`
}

type Permission struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`        // 权限名称
	Type        string `json:"type"`        // 权限类型：api-接口权限
	Description string `json:"description"` // 权限描述
	Resource    string `json:"resource"`    // 资源标识（如API路径）
	Action      string `json:"action"`      // 操作类型（如GET/POST等）
	Status      int    `json:"status"`      // 状态：0-禁用 1-启用
	CreateTime  int64  `json:"createTime"`
	UpdateTime  int64  `json:"updateTime"`
}

type CreatePermissionReq struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Description string `json:"description,optional"`
	Resource    string `json:"resource"`
	Action      string `json:"action"`
}

type UpdatePermissionReq struct {
	Id          int64  `json:"id"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	Resource    string `json:"resource,optional"`
	Action      string `json:"action,optional"`
	Status      int    `json:"status,optional"`
}

type PermissionListReq struct {
	Page     int    `json:"page,optional,default=1"`
	PageSize int    `json:"pageSize,optional,default=20"`
	Name     string `json:"name,optional"`
	Type     string `json:"type,optional"`
	Status   int    `json:"status,optional,default=-1"`
}

type PermissionListResp struct {
	Total int64        `json:"total"`
	List  []Permission `json:"list"`
}

type RolePermissionReq struct {
	RoleId        int64   `json:"roleId"`
	PermissionIds []int64 `json:"permissionIds"`
}

type RolePermissionResp struct {
	PermissionIds []int64 `json:"permissionIds"`
}

type BaseResp struct {
	Id int64 `json:"id,optional"`
}

type LivenessRequest struct {
}

type LivenessResponse struct {
}

type Request struct {
}

type Response struct {
}
