// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	zero "github/zjzjzjzj1874/go-zero-temp/zero/internal/handler/zero"
	"github/zjzjzjzj1874/go-zero-temp/zero/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/liveness",
				Handler: livenessHandler(serverCtx),
			},
		},
		rest.WithPrefix("/go-zero"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/swagger",
				Handler: zero.SwaggerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/swagger-bin",
				Handler: zero.SwaggerGetHandler(serverCtx),
			},
		},
		rest.WithPrefix("/zero"),
	)
}
